### PR TITLE
ci: add cloudbuild

### PR DESCRIPTION
**Pull request by kyessenov**
Signed-off-by: Kuat Yessenov <kuat@google.com>

### CODE REVIEW

**Comment by TristonianJones** [comment]
Build seems to be configured correctly, but I'm not sure why the timestamp related tests are failing.

**Comment by kyessenov** [comment]
```
```[ RUN      ] BuiltinsTest.TestTimestampFunctions
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
eval/public/builtin_func_test.cc:154: Failure
Expected equality of these values:
  result_value.IsInt64()
    Which is: false
  true
[  FAILED  ] BuiltinsTest.TestTimestampFunctions (64 ms)
```

Test is sensitive to the build environment probably. Will look further.

**Comment by TristonianJones** [comment]
I know Cloud Build has a problem with resolving timezone files in Go, perhaps this also applies in C++

**Comment by kyessenov** [comment]
@TristonianJones you are probably right. How did you get around it?

**Comment by TristonianJones** [comment]
@kyessenov I didn't, we had to disable the timezone related tests until we had time to figure out why ... still haven't had time.

**Comment by kyessenov** [comment]
Fixes #62 .

**Pull request merged**
