### PR TITLE
Export of internal changes

### PR DESCRIPTION
**Pull request by kyessenov**
```
305374137 by kuat <kuat@google.com>:

BEGIN_PUBLIC
Update the OSS build:

- update bazel to 3.0.0
- add flatbuffers WORKSPACE dependency
- add guards to status macro re-definitions
- update StatusOr fork to use ::value() instead of ::ValueOrDie()

END_PUBLIC

--
305143212 by kuat <kuat@google.com>:

BEGIN_PUBLIC
Implement FlatBuffers adapter from a reflection schema and a buffer.

The wrapper is implemented as a CelMap with the fields as the keys.
Each field provides a default value if not specified (which can optionally be changed). Strings take an empty string value by default. Because it is a map, the presence indicator simply means the field exists in the flatbuffer. To fully support the presence with the default values just like the protobuf, we would need to change the interpreter to support custom CelObjects that are not of type proto::Message*.

Nested objects are implemented as nested CelMaps.

Vectors of bytes and ubytes are represented as CEL bytes.

Vectors of other primitive fields are represented as CelLists of int64, uint64, or strings.

Vectors of objects are implemented in two ways:
1) CelList of CelMaps for each element by default.
2) CelMap of CelMaps indexed by the "key" string field in the nested table, if such field is present. This is identical to using LookupByKey feature, and compensates for the lack of the first-class dictionaries. The search is implemented using binary search and assumes the vectors are sorted.

Unions, enums, and strucst are not supported.
END_PUBLIC
--
304020956 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Add basic comprehension support for unknowns.
END_PUBLIC

--
303997613 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
change gunit dependency to prevent linker errors.
END_PUBLIC
--
302986282 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Update argument overload matching to only allow whitelisted functions to consume errors and unknown sets.
END_PUBLIC

--
302697412 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Add option for how to treat unset fields. Default is current behavior --
ignore them. Second option is to bind the default that the cc api provides for
the given field type.
END_PUBLIC
--
302456916 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Rollback: Bind fields even if not set using the bind proto to activation helper.
END_PUBLIC
--
302141179 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
rollback: Update argument overload matching to only allow whitelisted functions to consume errors and unknown sets.
END_PUBLIC

--
302125035 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
rollback: Add basic comprehension support for unknowns.
END_PUBLIC

--
302120264 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
rollback: Add attr trail to iter_var. This should allow unknown paths to be maintained in comprehensions.
END_PUBLIC

--
302072738 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Add attr trail to iter_var. This should allow unknown paths to be maintained in comprehensions.
END_PUBLIC
--
302072183 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Add basic comprehension support for unknowns.
END_PUBLIC
--
302071888 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Update argument overload matching to only allow whitelisted functions to consume errors and unknown sets.
END_PUBLIC
--
302066307 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Bind fields even if not set using the bind proto to activation helper.
END_PUBLIC
--
301842853 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Add general less than function for CelValues to enable use with sets.
END_PUBLIC

--
300820237 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
internal change
END_PUBLIC
--
300605074 by CEL Dev Team <cel-dev@google.com>:

BEGIN_PUBLIC
Internal change
END_PUBLIC
--
300163642 by CEL Dev Team <cel-dev@google.com>:
BEGIN_PUBLIC
internal change
END_PUBLIC
--
297641944 by kuat <kuat@google.com>:

BEGIN_PUBLIC
Add missing override to a member function
END_PUBLIC

PiperOrigin-RevId: 305374137
```

### CODE REVIEW

**Comment by kyessenov** [comment]
@TristonianJones do you happen to know if CI is still active here? I'm not seeing it triggered.

**Comment by TristonianJones** [comment]
@kyessenov I'll have to double check on the CI. I think you had mentioned there was an issue in the past, but I don't recall what happened from there. Let me get back to you.

**Comment by kyessenov** [comment]
Yeah, I think last time it showed up eventually. I'm really not sure what's happening there. It looks like you are using Travis on cel-go. We could migrate to something newer, but it would be better to keep it consistent.

**Comment by kyessenov** [comment]
It is actually still running: https://travis-ci.org/github/google/cel-cpp. I think what's missing is branch protection on master to gate by the check.

**Comment by kyessenov** [comment]
The build passed https://travis-ci.org/github/google/cel-cpp/builds/672360002

**Pull request merged**
